---
config:
  COM_PORT: "AUTO"
  THEME: Gotham92
  HW_SENSORS: STATIC
  ETH: ""
  WLO: ""
  CPU_FAN: AUTO
  PING: 127.0.0.1
  WEATHER_API_KEY: ""
  WEATHER_LATITUDE: -23.5505
  WEATHER_LONGITUDE: -46.6333
  WEATHER_UNITS: metric
  WEATHER_LANGUAGE: pt

display:
  REVISION: SIMU
  BRIGHTNESS: 30
  DISPLAY_REVERSE: false
  RESET_ON_STARTUP: false
