---
config:
  COM_PORT: "AUTO"
  THEME: Gotham92
  HW_SENSORS: AUTO
  ETH: ""
  WLO: ""
  CPU_FAN: AUTO
  PING: 8.8.8.8
  WEATHER_API_KEY: ""
  WEATHER_LATITUDE: -23.5505
  WEATHER_LONGITUDE: -46.6333
  WEATHER_UNITS: metric
  WEATHER_LANGUAGE: pt

display:
  REVISION: TUR_USB
  BRIGHTNESS: 30
  DISPLAY_REVERSE: false
  RESET_ON_STARTUP: false
